let clicktextID=document.getElementById('clicktext');
let clickbuttonID=document.getElementById('clickbutton');
let openshopbuttonID=document.getElementById('openshopbutton');
let exitshopbuttonID=document.getElementById('exitshopbutton');
let upgradebutton1ID=document.getElementById('upgradebutton1');
let counter=0;
let upgrade0=1;
clickbuttonID.addEventListener('click',function(){
	counter=counter+upgrade0;
	clicktext.textContent='Кликов сделано: '+counter;
	shoptext.textContent='Ваш баланс: '+counter;
});
upgradebutton1ID.addEventListener('click',function(){
	counter=counter-35;
	upgrade0=upgrade0+1;
	clicktext.textContent='Кликов сделано: '+counter;
	shoptext.textContent='Ваш баланс: '+counter;
});
openshopbuttonID.addEventListener('click',function(){
	clicktext.classList.add('hidden');
	clickbutton.classList.add('hidden');
	dropdownlist.classList.add('hidden');
	dropdownlistopenbutton.classList.add('hidden');
	dropdownopenmenu.classList.add('hidden');
	dropdownitemopenbutton1.classList.add('hidden');
	dropdownitemopenbutton2.classList.add('hidden');
	dropdownitemopenbutton3.classList.add('hidden');
	dropdowndivider.classList.add('hidden');
	dropdownitemopenbutton4.classList.add('hidden');
	openshopbutton.classList.add('hidden');
	openexchangebutton.classList.add('hidden');
	administratorskayapanelopenbutton.classList.add('hidden');
	shoptext.classList.remove('hidden');
	exitshopbutton.classList.remove('hidden');
	card1.classList.remove('hidden');
	cardimagetop1.classList.remove('hidden');
	cardbody1.classList.remove('hidden');
	cardtitle1.classList.remove('hidden');
	cardtext1.classList.remove('hidden');
	upgradebutton1.classList.remove('hidden');
	card2.classList.remove('hidden');
	cardimagetop2.classList.remove('hidden');
	cardbody2.classList.remove('hidden');
	cardtitle2.classList.remove('hidden');
	cardtext2.classList.remove('hidden');
	upgradebutton2.classList.remove('hidden');
	card3.classList.remove('hidden');
	cardimagetop3.classList.remove('hidden');
	cardbody3.classList.remove('hidden');
	cardtitle3.classList.remove('hidden');
	cardtext3.classList.remove('hidden');
	upgradebutton3.classList.remove('hidden');
	card4.classList.remove('hidden');
	cardimagetop4.classList.remove('hidden');
	cardbody4.classList.remove('hidden');
	cardtitle4.classList.remove('hidden');
	cardtext4.classList.remove('hidden');
	upgradebutton4.classList.remove('hidden');
	card5.classList.remove('hidden');
	cardimagetop5.classList.remove('hidden');
	cardbody5.classList.remove('hidden');
	cardtitle5.classList.remove('hidden');
	cardtext5.classList.remove('hidden');
	upgradebutton5.classList.remove('hidden');
});
exitshopbuttonID.addEventListener('click',function(){
	clicktext.classList.remove('hidden');
	clickbutton.classList.remove('hidden');
	dropdownlist.classList.remove('hidden');
	dropdownlistopenbutton.classList.remove('hidden');
	dropdownopenmenu.classList.remove('hidden');
	dropdownitemopenbutton1.classList.remove('hidden');
	dropdownitemopenbutton2.classList.remove('hidden');
	dropdownitemopenbutton3.classList.remove('hidden');
	dropdowndivider.classList.remove('hidden');
	dropdownitemopenbutton4.classList.remove('hidden');
	openshopbutton.classList.remove('hidden');
	openexchangebutton.classList.remove('hidden');
	administratorskayapanelopenbutton.classList.remove('hidden');
	shoptext.classList.add('hidden');
	exitshopbutton.classList.add('hidden');
	card1.classList.add('hidden');
	cardimagetop1.classList.add('hidden');
	cardbody1.classList.add('hidden');
	cardtitle1.classList.add('hidden');
	cardtext1.classList.add('hidden');
	upgradebutton1.classList.add('hidden');
	card2.classList.add('hidden');
	cardimagetop2.classList.add('hidden');
	cardbody2.classList.add('hidden');
	cardtitle2.classList.add('hidden');
	cardtext2.classList.add('hidden');
	upgradebutton2.classList.add('hidden');
	card3.classList.add('hidden');
	cardimagetop3.classList.add('hidden');
	cardbody3.classList.add('hidden');
	cardtitle3.classList.add('hidden');
	cardtext3.classList.add('hidden');
	upgradebutton3.classList.add('hidden');
	card4.classList.add('hidden');
	cardimagetop4.classList.add('hidden');
	cardbody4.classList.add('hidden');
	cardtitle4.classList.add('hidden');
	cardtext4.classList.add('hidden');
	upgradebutton4.classList.add('hidden');
	card5.classList.add('hidden');
	cardimagetop5.classList.add('hidden');
	cardbody5.classList.add('hidden');
	cardtitle5.classList.add('hidden');
	cardtext5.classList.add('hidden');
	upgradebutton5.classList.add('hidden');
});
